name: 📜 Protocol Release
permissions:
  "contents": "write"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string
      description:
        description: 'Description Text'
        required: false
        type: string
        default: ""

jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flatc
        uses: Nugine/setup-flatc@v1
        with:
          version: "24.3.25"

      - name: Generate Java code from FlatBuffers
        run: |
          mkdir -p generated/java
          flatc --java -o generated/java schemas/*.fbs
          

      - name: Generate TypeScript code from FlatBuffers
        run: |
          mkdir -p generated/ts/src
          flatc --ts -o generated/ts/src/ schemas/*.fbs

      - name: Create package.json
        run: |
          cat <<EOL > package.json
          {
            "name": "trackrails",
            "version": "1.0.0",
            "description": "TrackRails TypeScript for DataTracks",
            "main": "generated/ts/src/protocol.ts",
            "types": "generated/ts/src/protocol.ts",
            "repository": {
              "type": "git",
              "url": "https://github.com/data-tracks/TrackRails.git"
            },
            "license": "GPLv3"
          }

      - name: Generate Rust code from FlatBuffers
        run: |
          mkdir -p generated/rust/src
          flatc --rust -o generated/rust/src/ schemas/*.fbs

      - name: Create Cargo.toml and increment version for Rust Code
        run: |
          # Define the path to the Cargo.toml file
          CARGO_TOML_PATH="generated/rust/Cargo.toml"
          PACKAGE_NAME="track-rails"
      
          # Ensure the directory exists for the generated file
          mkdir -p "$(dirname "$CARGO_TOML_PATH")"
      
          # --- Determine the current version from crates.io ---
          CURRENT_VERSION="0.0.0" # Default starting version if API call fails or version not found
      
          echo "Attempting to fetch current version of '$PACKAGE_NAME' from crates.io..."
          # Fetch package information from crates.io API
          # We use -s for silent, -f for fail on errors, and jq to parse the JSON
          CRATES_IO_RESPONSE=$(curl -sSf "https://crates.io/api/v1/crates/$PACKAGE_NAME")
      
          if [ $? -eq 0 ] && [ -n "$CRATES_IO_RESPONSE" ]; then
          # Extract the max_version from the JSON response
          # Note: 'max_version' is the latest published version on crates.io
          FETCHED_VERSION=$(echo "$CRATES_IO_RESPONSE" | jq -r '.crate.max_version')
          
          if [ -n "$FETCHED_VERSION" ] && [[ "$FETCHED_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          CURRENT_VERSION="$FETCHED_VERSION"
          echo "Found current version on crates.io: $CURRENT_VERSION"
          else
          echo "Warning: Could not extract a valid version from crates.io response or response was empty. Using default 0.0.0"
          echo "crates.io response: $CRATES_IO_RESPONSE"
          fi
          else
          echo "Error fetching package info from crates.io for '$PACKAGE_NAME'. Using default 0.0.0"
          echo "Curl exit code: $?"
          fi
      
          # --- Increment the version ---
          # Split the version string into major, minor, and patch components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
      
          # Increment the patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
      
          echo "New version will be: $NEW_VERSION"
      
      
          ## Create Cargo 
          cat <<EOL > generated/rust/Cargo.toml
          [package]
          name = "track-rails"
          version = "0.0.1"
          authors = ["David Lengweiler <dave.lengw@gmail.com>"]
          description = "Rust Version of TrackRails Protocol."
          homepage = "https://github.com/data-tracks/TrackRails"
          repository = "https://github.com/data-tracks/TrackRails"
          keywords = ["stream", "data", "processing", "protocol"]
          license = "GPL-3.0-only"
          edition = "2024"
          readme = "README.md"

          [dependencies]
          flatbuffers = "25.2.10"
          
          [lib]
          path = "src/lib.rs" 
          version = "0.0.1"

          [build-dependencies]
          flatbuffers = "25.2.10"
          EOL
      - name: Create Cargo.toml for Rust Code
        run: |
          cat <<EOL > generated/rust/README.md
          # 🚂 TrackRails 
          ## DataTracks Communication Protocol 
  
          This crate contains the communication protocol for **DataTracks** using **FlatBuffers** for fast, efficient, and cross-platform data serialization.
          EOL

      - name: Create lib.rs for Rust code
        run: |
          mkdir -p generated/rust/src
          cat <<EOL > generated/rust/src/lib.rs
          pub mod message_generated;
          EOL

      - name: Commit generated code
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add generated/
          git add package.json
          git commit -m "Update generated code ${GITHUB_EVENT_INPUTS_VERSION}"

      - name: Push generated code to branch
        run: |
          git push origin HEAD:refs/heads/generated --force
